### ISSUE TITLE
Update 'Select the aggregates and constituents'

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/bluexp-automation#100]
### Summary

I noticed that the following page needs updating with the new FlexVol limits that came in 9.12.1P2, i.e. 300 TiB.

[https://docs.netapp.com/us-en/bluexp-automation/cm/wf_onprem_flexgroup_ontap_create_vol.html#1-select-the-working-environment](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.netapp.com%2Fus-en%2Fbluexp-automation%2Fcm%2Fwf_onprem_flexgroup_ontap_create_vol.html%231-select-the-working-environment&data=05%7C01%7CChanda.Jha%40netapp.com%7Ce3312a6780c64ff1fdd008db93c8c349%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638266262706103578%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2F0TB6qukqPQ1kDy0au9wDRHOLuyGKptF7Iq6TmAQtjk%3D&reserved=0)

•	Choose the desired value for the flexGroupVolumeInfo → numberOfConstituents input parameter.
As a general rule, the minimum or maximum size limit of a FlexGroup volume is based on the number of constituents. The maximum constituents number is 200; the minimum size of constituents is 100GB and the maximum size is **100TB**. For example, if you provide the value of the flexGroupVolumeInfo → numberOfConstituentsparameter as 10, the minimum volume size should be 100GB * 10 = 1TB and the maximum volume size should be **100TB** * 10 = 1000TB.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ranuk** [comment]
Thanks, Chanda. The data was supplied by the Engineering team. I'll talk to them internally and get back on this.

**Comment by netapp-ranuk** [comment]
Hi Chanda, The engineering team says that we have the applicative limit of maximum constituents’ number as 200, and maximum constituents’ member size as 100TB. We do not need to modify the documentation for now.
