### ISSUE TITLE
Product naming is not consistent

### ISSUE THREAD

**Issue by bdeloure** [NetAppDocs/bluexp-automation#110]
### Page URL

https://docs.netapp.com/us-en/bluexp-automation/fsx/overview.html

### Page title

Overview

### Summary

This section in the API documentation says "Amazon FSx for ONTAP service"
From what I have seen the first party AWS offering is called "Amazon FSx for NetApp ONTAP"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ranuk** [comment]
Thanks for reporting the issue. We'll investigate and fix this as soon as possible.

**Comment by netapp-ranuk** [comment]
Hi @bdeloure 

We have fixed the issue in the reference documentation to align with the official naming of the product.
