### ISSUE TITLE
Path not working in current format

### ISSUE THREAD

**Issue by cmackdev** [NetAppDocs/bluexp-automation#119]
### Page URL

https://docs.netapp.com/us-en/bluexp-automation/cm/wf_aws_ontap_get_aggrs.html

### Page title

Get aggregates

### Summary

Current Path: /occm/api/vsa/aggregates/{workingEnvironmentId}
Revised Working Path: /occm/api/vsa/aggregates?workingEnviornmentId=<workingEnvironmentId>

The example curl request will also need to be changed to reflect this. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ranuk** [comment]
Thanks for highlighting the issue. We'll investigate and get back as soon as possible.

**Comment by netapp-ranuk** [comment]
We have updated the path https://docs.netapp.com/us-en/bluexp-automation/cm/wf_aws_ontap_get_aggrs.html. 

Thank you!
