### ISSUE TITLE
404 File not found error when clicking Rest implementation under Response Headers

### ISSUE THREAD

**Issue by chuffster80** [NetAppDocs/bluexp-automation#81]
Page: [Overview](https://docs.netapp.com/us-en/cloud-manager-automation/credential/overview.html)

Getting 404 not found when clicking Rest implementation under Response Headers on this page. Link looks broken.

404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

[Read the full documentation](https://help.github.com/pages/) for more information about using GitHub Pages.

[GitHub Status](https://githubstatus.com/) — [@githubstatus](https://twitter.com/githubstatus)

**Comment by netapp-ranuk** [comment]
Thank you for reporting this issue. We'll rectify the link soon.

**Comment by netapp-ranuk** [comment]
Hi @chuffster80 The broken link has been fixed. Please see the [link](https://docs.netapp.com/us-en/bluexp-automation/credential/overview.html#query-parameters).
