### ISSUE TITLE
Summary doesn't match lead

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/bluexp-automation#85]
Page: [Hello world](https://docs.netapp.com/us-en/cloud-manager-automation/cm/hello_world.html)

The summary in the page's header is as follows:

> You can issue a curl command to get started using the Cloud Manager REST API and confirm its availability.

As a result, this text appears in search results. It doesn't match the lead.

**Comment by netapp-ranuk** [comment]
Thanks, Ben. I am working on rectifying this.

**Comment by netapp-ranuk** [comment]
Thanks, Chanda. We have resolved the issue.
